import { defineConfig } from "vite";

export default defineConfig({
  // Project Pages serve from /<repo>/, so assets must be requested from there.
  // Overridden to "/" for local dev by the dev server's own default.
  base: process.env.OMNIGRID_BASE ?? "/",
  server: { host: "127.0.0.1", port: 5173, strictPort: false },
  // data/dist is generated by the Python pipeline; public/data symlinks to it.
  publicDir: "public",
  build: { chunkSizeWarningLimit: 1200 },
});
