import { defineConfig } from "vite";

export default defineConfig({
  server: { host: "127.0.0.1", port: 5173, strictPort: false },
  // data/dist is generated by the Python pipeline; served as static assets.
  publicDir: "public",
});
